<?php
/**
 * AURALIS - централна карта на hreflang клъстерите за статиите.
 * Ключ: каноничният BG URL на статията. Стойност: преводните URL-и.
 * Ползва се от inc/article-template{,-it,-ro,-el}.php за авто-hreflang в <head> (it/ro/el/en/es).
 * Поддръжка: при нов език добави ключа тук (една точка на истина).
 */
$HREFLANG_CLUSTERS = [
  'https://tinnitus-app.help/articles/bimodalna-neuromodulatsiya.php' => ['it' => 'https://tinnitus-app.help/it/articoli/neuromodulazione-bimodale-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/neuromodulare-bimodala-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/dimodiki-neurodiamorfosi.php', 'en' => 'https://tinnitus-app.help/en/articles/bimodal-neuromodulation.php', 'es' => 'https://tinnitus-app.help/es/articulos/neuromodulacion-bimodal.php'],
  'https://tinnitus-app.help/articles/buchene-noshtem-ne-moga-da-zaspya.php' => ['it' => 'https://tinnitus-app.help/it/articoli/non-riesco-a-dormire-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/nu-pot-dormi-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/den-mporo-na-koimitho-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/cant-sleep-with-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/no-puedo-dormir-con-tinnitus.php'],
  'https://tinnitus-app.help/articles/depresiya-i-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/acufene-e-depressione.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tinitus-si-depresie.php', 'el' => 'https://tinnitus-app.help/el/arthra/emvoes-kai-katathlipsi.php', 'en' => 'https://tinnitus-app.help/en/articles/tinnitus-and-depression.php', 'es' => 'https://tinnitus-app.help/es/articulos/tinnitus-y-depresion.php'],
  'https://tinnitus-app.help/articles/dnevnik-na-sana-i-tinitusa.php' => ['it' => 'https://tinnitus-app.help/it/articoli/diario-sonno-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/jurnal-somn-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/imerologio-ypnou-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/sleep-and-tinnitus-diary.php', 'es' => 'https://tinnitus-app.help/es/articulos/diario-de-sueno-y-tinnitus.php'],
  'https://tinnitus-app.help/articles/kafe-alkohol-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/caffe-alcol-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/cafea-alcool-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/kafes-alkool-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/coffee-alcohol-and-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/cafe-alcohol-y-tinnitus.php'],
  'https://tinnitus-app.help/articles/lekarstva-prichinyavasht-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/farmaci-che-causano-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/medicamente-care-cauzeaza-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/farmaka-pou-prokaloun-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/medications-that-cause-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/medicamentos-que-causan-tinnitus.php'],
  'https://tinnitus-app.help/articles/magneziy-ginko-tsink-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/magnesio-ginkgo-zinco-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/magneziu-ginkgo-zinc-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/magnisio-ginkgo-psevdargyros-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/magnesium-ginkgo-zinc-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/magnesio-ginkgo-zinc-tinnitus.php'],
  'https://tinnitus-app.help/articles/maskirane-vs-notched.php' => ['it' => 'https://tinnitus-app.help/it/articoli/mascheramento-vs-notched.php', 'ro' => 'https://tinnitus-app.help/ro/articole/mascare-vs-notched.php', 'el' => 'https://tinnitus-app.help/el/arthra/maskarisma-vs-notched.php', 'en' => 'https://tinnitus-app.help/en/articles/masking-vs-notched.php', 'es' => 'https://tinnitus-app.help/es/articulos/enmascaramiento-vs-notched.php'],
  'https://tinnitus-app.help/articles/mindfulness-pri-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/mindfulness-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/mindfulness-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/mindfulness-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/mindfulness-for-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/mindfulness-para-el-tinnitus.php'],
  'https://tinnitus-app.help/articles/notched-zvukova-terapiya.php' => ['it' => 'https://tinnitus-app.help/it/articoli/terapia-del-suono-notched.php', 'ro' => 'https://tinnitus-app.help/ro/articole/terapia-sonora-notched.php', 'el' => 'https://tinnitus-app.help/el/arthra/ihotherapeia-notched.php', 'en' => 'https://tinnitus-app.help/en/articles/notched-sound-therapy.php', 'es' => 'https://tinnitus-app.help/es/articulos/terapia-sonora-notched.php'],
  'https://tinnitus-app.help/articles/opasen-li-e-shumat-v-ushite.php' => ['it' => 'https://tinnitus-app.help/it/articoli/il-rumore-mi-danneggia-udito.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tinitus-periculos-auz.php', 'el' => 'https://tinnitus-app.help/el/arthra/emvoes-epikindynes-akoi.php', 'en' => 'https://tinnitus-app.help/en/articles/is-tinnitus-dangerous-for-hearing.php', 'es' => 'https://tinnitus-app.help/es/articulos/es-peligroso-el-tinnitus-para-la-audicion.php'],
  'https://tinnitus-app.help/articles/pulsirasht-shum-v-ushite.php' => ['it' => 'https://tinnitus-app.help/it/articoli/acufene-pulsante.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tinitus-pulsatil.php', 'el' => 'https://tinnitus-app.help/el/arthra/sfygmikes-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/pulsatile-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/tinnitus-pulsatil.php'],
  'https://tinnitus-app.help/articles/shte-oglusheya-li-ot-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/diventero-sordo-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/voi-surzi-din-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/tha-koufatho-apo-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/will-i-go-deaf-from-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/me-quedare-sordo-por-tinnitus.php'],
  'https://tinnitus-app.help/articles/shum-v-ushite-noshtem.php' => ['it' => 'https://tinnitus-app.help/it/articoli/fischio-nelle-orecchie.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tiuit-in-urechi.php', 'el' => 'https://tinnitus-app.help/el/arthra/vouitos-sta-aftia.php', 'en' => 'https://tinnitus-app.help/en/articles/ringing-in-the-ears.php', 'es' => 'https://tinnitus-app.help/es/articulos/zumbido-en-los-oidos.php'],
  'https://tinnitus-app.help/articles/sluhovi-aparati-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/apparecchi-acustici-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/aparate-auditive-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/akoustika-varikoias-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/hearing-aids-for-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/audifonos-para-el-tinnitus.php'],
  'https://tinnitus-app.help/articles/tinitus-i-san.php' => ['it' => 'https://tinnitus-app.help/it/articoli/acufene-di-notte.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tinitus-noaptea.php', 'el' => 'https://tinnitus-app.help/el/arthra/emvoes-ti-nyhta.php', 'en' => 'https://tinnitus-app.help/en/articles/tinnitus-at-night.php', 'es' => 'https://tinnitus-app.help/es/articulos/tinnitus-por-la-noche.php'],
  'https://tinnitus-app.help/articles/trevozhnost-i-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/ansia-e-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/anxietate-si-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/anhos-kai-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/anxiety-and-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/ansiedad-y-tinnitus.php'],
  'https://tinnitus-app.help/articles/tservikalen-tinitus-shiya.php' => ['it' => 'https://tinnitus-app.help/it/articoli/acufene-e-cervicale.php', 'ro' => 'https://tinnitus-app.help/ro/articole/tinitus-si-cervicala.php', 'el' => 'https://tinnitus-app.help/el/arthra/emvoes-kai-afhenas.php', 'en' => 'https://tinnitus-app.help/en/articles/tinnitus-and-neck.php', 'es' => 'https://tinnitus-app.help/es/articulos/tinnitus-y-cervicales.php'],
  'https://tinnitus-app.help/articles/zaglahnali-ushi-pod-voda.php' => ['it' => 'https://tinnitus-app.help/it/articoli/orecchie-ovattate.php', 'ro' => 'https://tinnitus-app.help/ro/articole/urechi-infundate.php', 'el' => 'https://tinnitus-app.help/el/arthra/vouloumena-aftia.php', 'en' => 'https://tinnitus-app.help/en/articles/clogged-ears-underwater.php', 'es' => 'https://tinnitus-app.help/es/articulos/oidos-tapados.php'],
  'https://tinnitus-app.help/articles/zvukove-pri-tinitus.php' => ['it' => 'https://tinnitus-app.help/it/articoli/quali-suoni-per-acufene.php', 'ro' => 'https://tinnitus-app.help/ro/articole/ce-sunete-pentru-tinitus.php', 'el' => 'https://tinnitus-app.help/el/arthra/poioi-ihoi-gia-emvoes.php', 'en' => 'https://tinnitus-app.help/en/articles/which-sounds-help-tinnitus.php', 'es' => 'https://tinnitus-app.help/es/articulos/que-sonidos-ayudan-al-tinnitus.php'],
];

/** Връща преводите (it/ro/el/en/es) за даден каноничен BG URL, или празен масив. */
function hreflang_alts($bgUrl) {
  global $HREFLANG_CLUSTERS;
  return $HREFLANG_CLUSTERS[$bgUrl] ?? [];
}
